alias gcc="/usr/bin/c99 -Wall -pedantic"

#alias gcc="gcc \
#    -std=c99 -Wall -pedantic -pedantic-errors \
#    -Wno-missing-braces -Wextra -Wno-missing-field-initializers -Wformat=2 \
#    -Wswitch-default -Wswitch-enum -Wcast-align -Wpointer-arith \
#    -Wbad-function-cast -Wstrict-overflow=5 -Wstrict-prototypes -Winline \
#    -Wundef -Wnested-externs -Wcast-qual -Wshadow -Wunreachable-code \
#    -Wlogical-op -Wfloat-equal -Wstrict-aliasing=2 -Wredundant-decls \
#    -Wold-style-definition"

#alias g++="g++ \
#    -Wall -pedantic -pedantic-errors \
#    -Wno-missing-braces -Wextra -Wno-missing-field-initializers -Wformat=2 \
#    -Wswitch-default -Wswitch-enum -Wcast-align -Wpointer-arith \
#    -Wstrict-overflow=5 -Winline \
#    -Wundef -Wcast-qual -Wshadow -Wunreachable-code \
#    -Wlogical-op -Wfloat-equal -Wstrict-aliasing=2 -Wredundant-decls"

